services:
    nuxt:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - 80:3000
            - 443:3000
        deploy:
            restart_policy:
                condition: on-failure